/**
 * Horse gift (الحصان والأميرة) - 2,500 Coins
 *
 * - Preview  : inside the gift square, a tiny desert with a white horse and a princess: the horse rears up, neighs,
 *              lands, and the princess winks - looping, with wind streaks (before tapping).
 * - Animation (20 seconds):
 *      0 - 1.6s    the live room turns into a golden desert (sky, sun, dunes), wind and flying dust start
 *      1.2 - 4.4s  the white horse gallops in with the princess on its back, then stops in the middle
 *      5.0 - 6.2s  the horse rises on its two hind legs only, front legs lifted, and neighs
 *      7.0 - 11.2s the princess holds on, the horse pirouettes one full turn in a whirl of dust (second neigh)
 *      11.2s       the horse lands (thump + dust cloud)
 *      12.6 - 15s  the camera comes close to the princess, she winks
 *      15.4s       the princess disappears in a burst of sparkles
 *      17.3 - 19s  the horse gallops away to the right, the desert fades and the live room comes back
 *
 * Standalone file: put it in src/components/gifts/ next to HeartGift.tsx and WitchGift.tsx.
 * The sounds are generated by src/lib/horseSounds.ts (no audio files needed).
 * To use real recordings, put them in the PUBLIC folder and set the two URLs below:
 *     public/sounds/horse-neigh.mp3
 *     public/sounds/desert-wind.mp3
 * If a file is missing or cannot be decoded, the generated sound is played instead.
 */
import React, { useEffect, useRef } from 'react';
import type { GiftDefinition } from '../../lib/types';
import { playHorseSound } from '../../lib/horseSounds';

// ── Gift settings ────────────────────────────────────────────────────────
const PRICE = 2500;
const TOTAL_MS = 20000;          // the whole gift lasts 20 seconds
const TOTAL_S = TOTAL_MS / 1000;
const FADE_IN_S = 1.6;           // the live room turns into the desert
const FADE_OUT_S = 1.5;          // and comes back at the end
const REAR_DEG = 38;             // how high the horse rises (degrees)
const NEIGH_URL: string | undefined = undefined; // e.g. '/sounds/horse-neigh.mp3'
const WIND_URL: string | undefined = undefined;  // e.g. '/sounds/desert-wind.mp3'

const GOLD = '#f6c978';

// Timeline (seconds)
const T_ENTER_FROM = 1.2;
const T_ENTER_TO = 4.4;
const T_REAR_FROM = 5.0;
const T_SPIN_FROM = 7.0;
const T_SPIN_TO = 11.0;
const T_LAND = 11.2;
const T_ZOOM_FROM = 12.6;
const T_WINK = 14.35;
const T_VANISH = 15.45;
const T_EXIT_FROM = 17.3;

// Sound plan (hoof beats follow the gallops: coming in and going away)
const HOOFS = (() => {
  const a: { t: number; v: number }[] = [];
  let t = 1.3;
  while (t < 4.3) {
    const u = (t - T_ENTER_FROM) / (T_ENTER_TO - T_ENTER_FROM);
    const v = 0.2 + 0.6 * Math.sin(Math.min(1, u * 1.2) * Math.PI * 0.55);
    [0, 0.1, 0.2, 0.3].forEach((o, i) => a.push({ t: t + o, v: v * [1, 0.7, 0.8, 0.9][i] }));
    t += 0.6 + 0.6 * u;
  }
  t = T_EXIT_FROM + 0.1;
  while (t < 19.2) {
    const u = (t - T_EXIT_FROM) / 1.9;
    [0, 0.1, 0.2, 0.3].forEach((o, i) => a.push({ t: t + o, v: 0.75 * (1 - u) * [1, 0.7, 0.8, 0.9][i] }));
    t += 0.5;
  }
  return a;
})();
const SOUND_PLAN = {
  totalS: TOTAL_S,
  hoofs: HOOFS,
  thumps: [{ t: 5.15, v: 0.5 }, { t: T_LAND + 0.1, v: 1 }],
  neighs: [{ t: 5.5, dur: 1.7, power: 1 }, { t: 9.3, dur: 1.0, power: 0.8 }, { t: 16.9, dur: 1.3, power: 0.85 }],
  chimes: [{ t: T_WINK, kind: 'wink' as const }, { t: T_VANISH, kind: 'vanish' as const }],
  gusts: [{ t: 0.4, dur: 3, power: 0.5 }, { t: 5.8, dur: 6.5, power: 1 }, { t: 13.5, dur: 3, power: 0.55 }, { t: 17, dur: 2.5, power: 0.5 }],
};

// ── Small helpers ────────────────────────────────────────────────────────
const clamp01 = (x: number) => Math.min(1, Math.max(0, x));
const smooth = (x: number) => { const u = clamp01(x); return u * u * (3 - 2 * u); };
const easeOut = (x: number) => 1 - Math.pow(1 - clamp01(x), 3);
const bump = (t: number, a: number, d: number) => (t >= a && t <= a + d ? Math.sin((Math.PI * (t - a)) / d) : 0);

// ── The horse and the princess (one drawing, side view, facing right) ───────
// Local coordinates: the hind hooves stand at (100, 270).
const WHITE = '#fbfbfe';
const FAR = '#e3e7f3';
const OUTLINE = '#b3bad1';
const SKIN = '#ffdcc4';
const HAIR = '#7a3b2e';

function Leg({ p, x, y, far }: { p: string; x: number; y: number; far?: boolean }) {
  return (
    <g data-p={p} data-x={x} data-y={y} transform={`translate(${x} ${y})`}>
      <line x1="0" y1="0" x2="0" y2="44" stroke={OUTLINE} strokeWidth={far ? 17.5 : 19} strokeLinecap="round" />
      <line x1="0" y1="0" x2="0" y2="44" stroke={far ? FAR : WHITE} strokeWidth={far ? 15 : 16.5} strokeLinecap="round" />
      <g data-k={p} transform="translate(0 44)">
        <line x1="0" y1="0" x2="0" y2="42" stroke={OUTLINE} strokeWidth={far ? 12.5 : 14} strokeLinecap="round" />
        <line x1="0" y1="0" x2="0" y2="42" stroke={far ? FAR : WHITE} strokeWidth={far ? 10 : 11.5} strokeLinecap="round" />
        <path d="M -7.5 38 L 7.5 38 L 8.5 49 L -8.5 49 Z" fill="#8c7a66" />
      </g>
    </g>
  );
}

function HorseParts() {
  return (
    <g>
      <defs>
        <linearGradient id="hg-gold" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stopColor="#fbe7a0" />
          <stop offset="1" stopColor="#d49a3c" />
        </linearGradient>
        <linearGradient id="hg-dress" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stopColor="#c98cff" />
          <stop offset="1" stopColor="#7a4fd6" />
        </linearGradient>
      </defs>

      {/* far legs */}
      <Leg p="hf" x={116} y={176} far />
      <Leg p="ff" x={182} y={178} far />

      {/* tail */}
      <g data-p="tail">
        <path d="M92 146 C60 138 38 170 46 222 C50 244 66 252 71 236 C62 210 70 182 97 164 Z" fill="url(#hg-gold)" stroke="#c8963c" strokeWidth="1" />
        <path d="M84 150 C62 156 52 184 56 214" fill="none" stroke="#fff3c4" strokeWidth="2" strokeLinecap="round" opacity=".7" />
      </g>

      {/* body */}
      <path d="M92 150 C100 124 150 118 192 128 L206 140 C214 172 200 192 170 196 C140 200 110 198 98 186 C84 176 84 160 92 150 Z" fill={WHITE} stroke={OUTLINE} strokeWidth="1.5" />
      <path d="M98 186 C110 198 140 200 170 196 C196 192 210 172 206 150 C200 176 170 188 140 188 C118 188 104 182 98 170 Z" fill="#e3e7f1" opacity=".85" />

      {/* near legs */}
      <Leg p="hn" x={100} y={176} />
      <Leg p="fn" x={196} y={178} />

      {/* neck */}
      <path d="M190 126 C205 100 225 78 242 62 L268 92 C250 108 232 132 210 162 Z" fill={WHITE} stroke={OUTLINE} strokeWidth="1.5" />

      {/* mane */}
      <g data-p="mane">
        <path d="M242 58 C222 54 196 80 182 124 C176 140 192 146 198 132 C204 112 222 92 248 74 Z" fill="url(#hg-gold)" stroke="#c8963c" strokeWidth="1" />
        <path d="M236 66 C214 74 196 100 192 130" fill="none" stroke="#fff3c4" strokeWidth="2" strokeLinecap="round" opacity=".7" />
      </g>

      {/* head */}
      <g data-p="head">
        <path d="M236 62 C252 56 270 74 296 104 C302 112 298 124 288 124 C278 124 262 112 250 100 C240 90 232 76 236 62 Z" fill={WHITE} stroke={OUTLINE} strokeWidth="1.5" />
        <path d="M240 58 L243 34 L255 56 Z" fill={WHITE} stroke={OUTLINE} strokeWidth="1.5" />
        <path d="M244 52 L245 42 L250 54 Z" fill="#f4c9d0" />
        <path d="M238 58 C250 52 262 62 258 78 C252 68 246 64 238 66 Z" fill="url(#hg-gold)" />
        <ellipse cx="256" cy="80" rx="3.2" ry="2.5" fill="#2b2230" />
        <circle cx="257" cy="79.2" r="0.9" fill="#fff" />
        <ellipse cx="292" cy="113" rx="2" ry="1.5" fill="#b79aa0" />
        <path d="M288 122 C280 120 272 114 266 108" fill="none" stroke="#c9a2a8" strokeWidth="1.3" strokeLinecap="round" />
        <path d="M250 70 L282 108" fill="none" stroke="#c8963c" strokeWidth="2.4" strokeLinecap="round" />
        <path d="M276 100 C281 99 285 103 284 108" fill="none" stroke="#c8963c" strokeWidth="2" strokeLinecap="round" />
      </g>

      {/* princess */}
      <g data-p="princess">
        <g data-p="hair">
          <path d="M142 36 C120 36 104 70 112 108 C108 120 122 122 128 108 C134 90 140 70 146 56 Z" fill={HAIR} />
        </g>
        {/* gown over the horse's back */}
        <path d="M130 108 L172 108 C190 122 204 150 204 168 C176 178 126 180 104 170 C116 150 124 128 130 108 Z" fill="url(#hg-dress)" stroke="#5b36b0" strokeWidth="1" />
        <path d="M104 170 C126 180 176 178 204 168" fill="none" stroke="#f6c744" strokeWidth="3" strokeLinecap="round" />
        <path d="M150 118 C150 140 146 158 140 176" fill="none" stroke="#e9d6ff" strokeWidth="1.4" opacity=".6" />
        {/* body */}
        <path d="M138 114 C136 98 140 82 144 70 L162 70 C166 82 170 98 168 114 Z" fill="#f06ca0" stroke="#c9457f" strokeWidth="1" />
        <path d="M139 100 L167 100" stroke="#f6c744" strokeWidth="3" />
        {/* arm holding the mane */}
        <path d="M164 78 C180 80 196 90 206 104" fill="none" stroke={SKIN} strokeWidth="6" strokeLinecap="round" />
        <path d="M164 78 C172 79 180 82 186 87" fill="none" stroke="#f06ca0" strokeWidth="8" strokeLinecap="round" />
        <circle cx="207" cy="105" r="4.6" fill={SKIN} />
        {/* neck + head */}
        <rect x="148" y="62" width="10" height="12" fill={SKIN} />
        <circle cx="153" cy="52" r="15" fill={SKIN} stroke="#e8b99d" strokeWidth="0.8" />
        <path d="M138 50 C138 34 168 32 168 50 C160 42 148 42 138 50 Z" fill={HAIR} />
        <path d="M139 50 C136 60 137 70 141 78 C140 66 141 58 143 52 Z" fill={HAIR} />
        <path d="M167 50 C170 60 169 68 166 74 C167 64 166 58 165 52 Z" fill={HAIR} />
        {/* eyes */}
        <g>
          <ellipse cx="147" cy="52" rx="3.4" ry="3.8" fill="#fff" />
          <circle cx="147.4" cy="52.2" r="2.3" fill="#3a6fd0" />
          <circle cx="147.4" cy="52.2" r="1.1" fill="#1a1a2e" />
          <circle cx="146.6" cy="51.2" r="0.7" fill="#fff" />
          <path d="M143.6 50 Q147 47.2 150.6 50" fill="none" stroke="#3a2224" strokeWidth="1.2" strokeLinecap="round" />
        </g>
        <g data-p="eyeO">
          <ellipse cx="159" cy="52" rx="3.4" ry="3.8" fill="#fff" />
          <circle cx="159.4" cy="52.2" r="2.3" fill="#3a6fd0" />
          <circle cx="159.4" cy="52.2" r="1.1" fill="#1a1a2e" />
          <circle cx="158.6" cy="51.2" r="0.7" fill="#fff" />
          <path d="M155.6 50 Q159 47.2 162.6 50" fill="none" stroke="#3a2224" strokeWidth="1.2" strokeLinecap="round" />
        </g>
        <path data-p="eyeS" d="M155.2 52.6 Q159 49.4 162.8 52.6" fill="none" stroke="#3a2224" strokeWidth="1.8" strokeLinecap="round" opacity="0" />
        <path d="M143 46 Q147 44 151 46 M155 46 Q159 44 163 46" fill="none" stroke={HAIR} strokeWidth="1.1" strokeLinecap="round" />
        <circle cx="142" cy="60" r="3.2" fill="#ff8fa8" opacity=".35" />
        <circle cx="164" cy="60" r="3.2" fill="#ff8fa8" opacity=".35" />
        <path d="M153 56 L152 58.5 L154 58.5" fill="none" stroke="#e0a98f" strokeWidth="0.8" strokeLinecap="round" />
        <path d="M149 61 Q153 65 157 61" fill="none" stroke="#c2455f" strokeWidth="1.5" strokeLinecap="round" />
        {/* crown */}
        <path d="M142 38 L143 27 L148 33 L153 24 L158 33 L163 27 L164 38 Z" fill="#f6c744" stroke="#c8962a" strokeWidth="0.8" />
        <circle cx="153" cy="31" r="1.7" fill="#e8408a" />
      </g>
    </g>
  );
}

// ── Posing the drawing from code ────────────────────────────────────────────
interface LegRef { g: SVGGElement; k: SVGGElement; x: number; y: number }
interface Parts {
  fn: LegRef; ff: LegRef; hn: LegRef; hf: LegRef;
  head: SVGGElement; mane: SVGGElement; tail: SVGGElement; hair: SVGGElement;
  eyeO: SVGGElement; eyeS: SVGGElement; princess: SVGGElement;
}
interface Pose {
  g: number;        // gallop phase
  run: number;      // 0..1 how much the horse runs
  rear: number;     // 0..1 how high the front is raised
  paw: number;      // time for the pawing in the air
  neigh: number;    // 0..1 head toss while neighing
  wobble: number;   // time for the hair / mane / tail
  wink: number;     // 0..1 the princess's right eye closed
  vanish: number;   // 0..1 the princess fades away
}

function getParts(root: Element): Parts | null {
  const q = (sel: string) => root.querySelector(sel) as SVGGElement | null;
  const leg = (id: string): LegRef | null => {
    const g = q(`[data-p="${id}"]`);
    const k = q(`[data-k="${id}"]`);
    if (!g || !k) return null;
    return { g, k, x: Number(g.getAttribute('data-x')), y: Number(g.getAttribute('data-y')) };
  };
  const fn = leg('fn'), ff = leg('ff'), hn = leg('hn'), hf = leg('hf');
  const head = q('[data-p="head"]'), mane = q('[data-p="mane"]'), tail = q('[data-p="tail"]'), hair = q('[data-p="hair"]');
  const eyeO = q('[data-p="eyeO"]'), eyeS = q('[data-p="eyeS"]'), princess = q('[data-p="princess"]');
  if (!fn || !ff || !hn || !hf || !head || !mane || !tail || !hair || !eyeO || !eyeS || !princess) return null;
  return { fn, ff, hn, hf, head, mane, tail, hair, eyeO, eyeS, princess };
}

function applyPose(P: Parts, o: Pose) {
  const { g, run, rear, paw, neigh, wobble, wink, vanish } = o;
  const s = Math.sin;
  const setLeg = (l: LegRef, up: number, kn: number) => {
    l.g.setAttribute('transform', `translate(${l.x} ${l.y}) rotate(${up.toFixed(1)})`);
    l.k.setAttribute('transform', `translate(0 44) rotate(${Math.max(0, kn).toFixed(1)})`);
  };
  setLeg(P.fn, run * 32 * s(g) - 52 * rear, run * (32 + 32 * s(g + 1.2)) + rear * (78 + 18 * s(paw * 7)));
  setLeg(P.ff, run * 32 * s(g + 0.9) - 44 * rear + 5 * rear * s(paw * 7 + 1.2), run * (32 + 32 * s(g + 2.1)) + rear * (70 + 16 * s(paw * 7 + 2.3)));
  setLeg(P.hn, run * 30 * s(g + Math.PI), run * (28 + 28 * s(g + Math.PI + 1.2)));
  setLeg(P.hf, run * 30 * s(g + Math.PI + 0.9), run * (28 + 28 * s(g + Math.PI + 2.1)));

  P.head.setAttribute('transform', `rotate(${(-16 * neigh * (0.7 + 0.3 * s(wobble * 20))).toFixed(1)} 236 84)`);
  P.mane.setAttribute('transform', `rotate(${(3 * s(wobble * 6 + 1) + run * 4 + neigh * 5).toFixed(1)} 225 95)`);
  P.tail.setAttribute('transform', `rotate(${(4 * s(wobble * 5) + run * 7).toFixed(1)} 92 148)`);
  P.hair.setAttribute('transform', `rotate(${(3 * s(wobble * 5 + 2) + run * 6).toFixed(1)} 148 45)`);

  P.eyeO.setAttribute('opacity', wink > 0.5 ? '0' : '1');
  P.eyeS.setAttribute('opacity', wink > 0.5 ? '1' : '0');
  P.princess.setAttribute('opacity', String(1 - vanish));
  P.princess.setAttribute('transform', `translate(0 ${(-18 * vanish).toFixed(1)})`);
}

// ── Preview inside the gift square: tiny desert, horse rears, princess winks ─
const CSS = `
@keyframes hg-streak { 0% { transform: translateX(-120%); opacity: 0; } 20% { opacity: 1; } 100% { transform: translateX(520%); opacity: 0; } }
@media (prefers-reduced-motion: reduce) { .hg-streak { animation: none !important; } }
`;

const PERIOD = 5.2;

function HorsePreview({ size = 72 }: { size?: number }) {
  const s = Math.round(size * 1.2);
  const hRef = useRef<SVGGElement>(null);

  useEffect(() => {
    const root = hRef.current;
    if (!root) return;
    const parts = getParts(root);
    if (!parts) return;
    let raf = 0;
    const t0 = performance.now();
    let gPhase = 0;
    let last = t0;
    const frame = (now: number) => {
      const t = ((now - t0) / 1000) % PERIOD;
      const dt = Math.min(0.05, (now - last) / 1000);
      last = now;
      const run = t < 1 ? 0.9 * (1 - t) : 0;
      gPhase += dt * (5 + 10 * run);
      const rear = smooth((t - 1.2) / 0.7) * (1 - smooth((t - 3.3) / 0.7));
      const neigh = bump(t, 1.7, 1.2);
      const wink = smooth((t - 4.0) / 0.1) * (1 - smooth((t - 4.45) / 0.12));
      applyPose(parts, { g: gPhase, run, rear, paw: t, neigh, wobble: t, wink, vanish: 0 });
      root.setAttribute('transform', `translate(100 270) rotate(${(-30 * rear).toFixed(1)}) translate(-100 -270)`);
      raf = requestAnimationFrame(frame);
    };
    raf = requestAnimationFrame(frame);
    return () => cancelAnimationFrame(raf);
  }, []);

  return (
    <div
      aria-hidden="true"
      style={{
        position: 'relative', width: s, height: s, borderRadius: 16, overflow: 'hidden',
        boxShadow: `0 0 0 1.5px ${GOLD}, 0 0 12px rgba(246,201,120,0.55)`,
        background: 'linear-gradient(180deg,#4f78b5 0%,#eba27a 48%,#f8d8a2 66%)',
      }}
    >
      <style>{CSS}</style>
      <div style={{ position: 'absolute', left: '66%', top: '16%', width: '16%', height: '16%', borderRadius: '50%', background: '#fff4cf', boxShadow: '0 0 14px 6px rgba(255,236,180,0.7)' }} />
      <div style={{ position: 'absolute', left: '-30%', width: '110%', bottom: '24%', height: '40%', borderRadius: '50%', background: '#d79a7c' }} />
      <div style={{ position: 'absolute', left: '15%', width: '120%', bottom: '-20%', height: '52%', borderRadius: '50%', background: '#ecc58d' }} />
      <svg viewBox="-20 0 330 285" preserveAspectRatio="xMidYMax meet" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%' }}>
        <ellipse cx="150" cy="273" rx="95" ry="8" fill="rgba(90,50,25,0.28)" />
        <g ref={hRef}><HorseParts /></g>
      </svg>
      {[18, 34, 52, 70].map((top, i) => (
        <div
          key={i}
          className="hg-streak"
          style={{
            position: 'absolute', left: 0, top: `${top}%`, width: '20%', height: 1.5,
            background: 'linear-gradient(90deg, transparent, rgba(255,240,205,0.95), transparent)',
            animation: `hg-streak ${1.5 + i * 0.25}s linear ${i * 0.4}s infinite`,
          }}
        />
      ))}
    </div>
  );
}

// ── Full-screen animation: desert, wind, dust, horse and princess ───────────
interface WindP { x: number; y: number; vx: number; vy: number; big: boolean; ph: number }
interface Puff { x: number; y: number; vx: number; vy: number; r: number; gr: number; age: number; life: number }
interface Spark { x: number; y: number; vx: number; vy: number; s: number; age: number; life: number; ph: number; col: string }

const duneD = (W: number, H: number, base: number, a1: number, k1: number, a2: number, k2: number, ph: number) => {
  let d = `M 0 ${H}`;
  for (let x = 0; x <= 2 * W + 12; x += 12) {
    const y = base + a1 * Math.sin((2 * Math.PI * k1 * x) / W + ph) + a2 * Math.sin((2 * Math.PI * k2 * x) / W + ph * 1.7);
    d += ` L ${x} ${y.toFixed(1)}`;
  }
  return d + ` L ${2 * W + 12} ${H} Z`;
};

function HorseAnimation({ onDone }: { onDone: () => void }) {
  const doneRef = useRef(onDone);
  doneRef.current = onDone;
  const wrapRef = useRef<HTMLDivElement>(null);
  const svgRef = useRef<SVGSVGElement>(null);
  const cvRef = useRef<HTMLCanvasElement>(null);
  const hazeRef = useRef<HTMLDivElement>(null);
  const sunRef = useRef<SVGCircleElement>(null);
  const glowRef = useRef<SVGCircleElement>(null);
  const layerRefs = useRef<(SVGGElement | null)[]>([]);
  const pathRefs = useRef<(SVGPathElement | null)[]>([]);
  const camRef = useRef<SVGGElement>(null);
  const horseRef = useRef<SVGGElement>(null);
  const shadowRef = useRef<SVGEllipseElement>(null);

  useEffect(() => {
    const wrap = wrapRef.current, svg = svgRef.current, cv = cvRef.current, haze = hazeRef.current;
    const sun = sunRef.current, glow = glowRef.current, cam = camRef.current, horse = horseRef.current, shadow = shadowRef.current;
    if (!wrap || !svg || !cv || !haze || !sun || !glow || !cam || !horse || !shadow) return;
    const c = cv.getContext('2d');
    const parts = getParts(horse);
    if (!c || !parts) return;

    let finished = false;
    const finish = () => {
      if (finished) return;
      finished = true;
      doneRef.current();
    };

    // sizes + the desert layers (dunes are drawn twice as wide so they can scroll without a seam)
    let W = window.innerWidth;
    let H = window.innerHeight;
    const LAYERS = [
      { base: 0.56, a1: 0.028, k1: 1, a2: 0.012, k2: 3, ph: 0.4, rate: 0.08 },
      { base: 0.63, a1: 0.03, k1: 1, a2: 0.014, k2: 2, ph: 2.1, rate: 0.2 },
      { base: 0.7, a1: 0.026, k1: 2, a2: 0.01, k2: 3, ph: 4.0, rate: 0.45 },
      { base: 0.78, a1: 0.016, k1: 2, a2: 0.008, k2: 5, ph: 1.2, rate: 1 },
    ];
    const resize = () => {
      W = window.innerWidth;
      H = window.innerHeight;
      const dpr = Math.min(2, window.devicePixelRatio || 1);
      cv.width = Math.round(W * dpr);
      cv.height = Math.round(H * dpr);
      cv.style.width = W + 'px';
      cv.style.height = H + 'px';
      c.setTransform(dpr, 0, 0, dpr, 0, 0);
      svg.setAttribute('viewBox', `0 0 ${W} ${H}`);
      sun.setAttribute('cx', String(W * 0.74)); sun.setAttribute('cy', String(H * 0.36)); sun.setAttribute('r', String(H * 0.055));
      glow.setAttribute('cx', String(W * 0.74)); glow.setAttribute('cy', String(H * 0.36)); glow.setAttribute('r', String(H * 0.22));
      LAYERS.forEach((L, i) => {
        pathRefs.current[i]?.setAttribute('d', duneD(W, H, H * L.base, H * L.a1, L.k1, H * L.a2, L.k2, L.ph));
      });
    };
    resize();
    window.addEventListener('resize', resize);

    const stopSound = playHorseSound({ ...SOUND_PLAN, neighUrl: NEIGH_URL, windUrl: WIND_URL });

    // particles
    const wind: WindP[] = [];
    const puffs: Puff[] = [];
    const sparks: Spark[] = [];
    let spawnW = 0, tPuffRun = 0, tPuffSpin = 0;
    let gPhase = 0, scroll = 0;
    let doneRear = false, doneLand = false, doneWink = false, doneVanish = false;

    const addPuff = (x: number, y: number, vx: number, vy: number, r: number, life: number, gr: number) => {
      if (puffs.length < 90) puffs.push({ x, y, vx, vy, r, gr, age: 0, life });
    };
    const addSpark = (x: number, y: number, vx: number, vy: number, s: number, life: number) => {
      const cols = ['#ffffff', '#ffe9a6', '#ffc2e0', '#fff6d0'];
      sparks.push({ x, y, vx, vy, s, age: 0, life, ph: Math.random() * 6, col: cols[(Math.random() * cols.length) | 0] });
    };
    const star = (x: number, y: number, s: number) => {
      c.beginPath();
      c.moveTo(x, y - s);
      c.quadraticCurveTo(x + s * 0.15, y - s * 0.15, x + s, y);
      c.quadraticCurveTo(x + s * 0.15, y + s * 0.15, x, y + s);
      c.quadraticCurveTo(x - s * 0.15, y + s * 0.15, x - s, y);
      c.quadraticCurveTo(x - s * 0.15, y - s * 0.15, x, y - s);
      c.fill();
    };

    let raf = 0;
    const t0 = performance.now();
    let last = t0;

    const frame = (now: number) => {
      const t = (now - t0) / 1000;
      const dt = Math.min(0.05, (now - last) / 1000);
      last = now;

      wrap.style.opacity = String(clamp01(t / FADE_IN_S) * clamp01((TOTAL_S - t) / FADE_OUT_S));

      const S = Math.min((W * 0.9) / 300, (H * 0.46) / 250);
      const gy = H * 0.82;
      const Xc = W * 0.5 - 40 * S;
      const X0 = -300 * S;
      const X1 = W + 80 * S;

      // horse position and how much it runs
      let X: number, run: number;
      if (t < T_ENTER_TO) {
        const u = clamp01((t - T_ENTER_FROM) / (T_ENTER_TO - T_ENTER_FROM));
        X = X0 + (Xc - X0) * easeOut(u);
        run = t < T_ENTER_FROM ? 1 : u < 1 ? Math.pow(1 - u, 0.7) : 0;
      } else if (t < T_EXIT_FROM) {
        X = Xc; run = 0;
      } else {
        const u = clamp01((t - T_EXIT_FROM) / 1.9);
        X = Xc + (X1 - Xc) * u * u;
        run = Math.min(1, 0.4 + u);
      }
      gPhase += dt * (5 + 10 * run);

      const rear = smooth((t - T_REAR_FROM) / 1.2) * (1 - smooth((t - T_LAND) / 1.1));
      const th = 2 * Math.PI * smooth((t - T_SPIN_FROM) / (T_SPIN_TO - T_SPIN_FROM));
      const sx = Math.cos(th);
      const ax = Math.max(0.05, Math.abs(sx)) * (sx < 0 ? -1 : 1);
      const neigh = Math.max(bump(t, 5.5, 1.7), bump(t, 9.3, 1.0), bump(t, 16.9, 1.3));
      const k = smooth((t - T_ZOOM_FROM) / 1.4) * (1 - smooth((t - 15.8) / 1.2));
      const wink = smooth((t - T_WINK) / 0.12) * (1 - smooth((t - (T_WINK + 0.6)) / 0.15));
      const vanish = smooth((t - T_VANISH) / 0.8);
      const bob = run * 7 * Math.abs(Math.sin(gPhase));
      const rot = -REAR_DEG * rear + rear * 2 * Math.sin(t * 3);

      applyPose(parts, { g: gPhase, run, rear, paw: t, neigh, wobble: t, wink, vanish });
      horse.setAttribute('transform', `translate(${X.toFixed(1)} ${(gy - bob).toFixed(1)}) scale(${(ax * S).toFixed(3)} ${S.toFixed(3)}) rotate(${rot.toFixed(2)}) translate(-100 -270)`);

      // shadow on the sand
      shadow.setAttribute('cx', (X + 45 * S * sx).toFixed(1));
      shadow.setAttribute('cy', (gy + 4 * S).toFixed(1));
      shadow.setAttribute('rx', (70 * S * (0.55 + 0.45 * Math.abs(sx)) * (1 - 0.3 * rear)).toFixed(1));
      shadow.setAttribute('ry', (9 * S).toFixed(1));

      // camera: comes close to the princess's face
      const hx = Xc + 53 * S, hy = gy + (52 - 270) * S;
      const cx = hx + (W / 2 - hx) * k, cy = hy + (H * 0.42 - hy) * k;
      const z = 1 + 2.0 * k;
      cam.setAttribute('transform', `translate(${cx.toFixed(1)} ${cy.toFixed(1)}) scale(${z.toFixed(3)}) translate(${(-hx).toFixed(1)} ${(-hy).toFixed(1)})`);

      // desert scrolls behind the running horse
      scroll += dt * (run * W * 0.95 + W * 0.03);
      LAYERS.forEach((L, i) => {
        layerRefs.current[i]?.setAttribute('transform', `translate(${(-((scroll * L.rate) % W)).toFixed(1)} 0)`);
      });

      // ── dust and sparkles ────────────────────────────────────────────────
      const windI = (0.5 + 0.55 * bump(t, 5.6, 6.4)) * smooth(t / 1.5) * (1 - 0.5 * k) * clamp01((TOTAL_S - t) / 1.5);
      haze.style.opacity = String(0.22 * windI);

      spawnW += dt * windI * W * 0.5;
      while (spawnW >= 1 && wind.length < 360) {
        spawnW -= 1;
        wind.push({
          x: -20, y: Math.random() * H * 0.98,
          vx: (350 + Math.random() * 650) * (0.6 + 0.7 * windI), vy: (Math.random() - 0.5) * 40,
          big: Math.random() < 0.25, ph: Math.random() * 6,
        });
      }

      // hoof dust while galloping
      tPuffRun += dt;
      if (run > 0.25 && tPuffRun > 0.07) {
        tPuffRun = 0;
        addPuff(X + Math.random() * 100 * S, gy + (Math.random() * 8) * S, -60 - Math.random() * 80, -20 - Math.random() * 30, 6 * S + Math.random() * 6 * S, 0.8, 38 * S);
      }
      // rear-up push
      if (!doneRear && t >= T_REAR_FROM + 0.1) {
        doneRear = true;
        for (let i = 0; i < 10; i++) addPuff(X + (Math.random() * 60 - 10) * S, gy, (Math.random() - 0.5) * 220, -30 - Math.random() * 60, 8 * S, 1.1, 50 * S);
      }
      // whirl of dust while spinning
      tPuffSpin += dt;
      if (t > T_SPIN_FROM && t < T_SPIN_TO + 0.2 && tPuffSpin > 0.035) {
        tPuffSpin = 0;
        const a = th * 2 + Math.random() * 6.28;
        const R = (60 + Math.random() * 40) * S;
        addPuff(X + Math.cos(a) * R, gy + Math.sin(a) * R * 0.2, -Math.sin(a) * 190, -20 - Math.random() * 40, 7 * S, 0.9, 44 * S);
      }
      // landing cloud
      if (!doneLand && t >= T_LAND + 0.1) {
        doneLand = true;
        for (let i = 0; i < 16; i++) addPuff(X + (Math.random() * 90 - 20) * S, gy + Math.random() * 6 * S, (Math.random() - 0.5) * 300, -20 - Math.random() * 50, 9 * S, 1.3, 60 * S);
      }
      // sparkle at the winking eye
      if (!doneWink && t >= T_WINK) {
        doneWink = true;
        for (let i = 0; i < 8; i++) addSpark(cx + 6 * S * z, cy, (Math.random() - 0.5) * 140, -Math.random() * 90, (3 + Math.random() * 4) * Math.max(1, z * 0.6), 0.9 + Math.random() * 0.5);
      }
      // the princess disappears in sparkles
      if (!doneVanish && t >= T_VANISH + 0.1) {
        doneVanish = true;
        for (let i = 0; i < 54; i++) {
          const a = Math.random() * 6.28, sp = 40 + Math.random() * 220;
          addSpark(cx + (Math.random() - 0.5) * 50 * S * z * 0.5, cy + (Math.random() - 0.3) * 120 * S * z * 0.4, Math.cos(a) * sp, Math.sin(a) * sp - 30, (3 + Math.random() * 6) * Math.max(1, z * 0.6), 0.9 + Math.random() * 0.9);
        }
      }

      c.clearRect(0, 0, W, H);

      // dust puffs
      for (let i = puffs.length - 1; i >= 0; i--) {
        const p = puffs[i];
        p.age += dt;
        if (p.age >= p.life) { puffs[i] = puffs[puffs.length - 1]; puffs.pop(); continue; }
        p.x += p.vx * dt + 60 * windI * dt;
        p.y += p.vy * dt;
        p.vx *= 0.985;
        p.r += p.gr * dt;
        const a = (1 - p.age / p.life) * 0.55;
        const g = c.createRadialGradient(p.x, p.y, 0, p.x, p.y, p.r);
        g.addColorStop(0, `rgba(236,206,160,${a})`);
        g.addColorStop(1, 'rgba(236,206,160,0)');
        c.fillStyle = g;
        c.beginPath();
        c.arc(p.x, p.y, p.r, 0, Math.PI * 2);
        c.fill();
      }

      // wind-blown sand streaks
      c.lineCap = 'round';
      [false, true].forEach(big => {
        c.strokeStyle = big ? 'rgba(246,222,176,0.5)' : 'rgba(246,222,176,0.32)';
        c.lineWidth = big ? 2.4 : 1.2;
        c.beginPath();
        for (let i = wind.length - 1; i >= 0; i--) {
          const p = wind[i];
          if (p.big !== big) continue;
          p.x += p.vx * dt;
          p.y += p.vy * dt + Math.sin(t * 3 + p.ph) * 14 * dt;
          if (p.x > W + 40) { wind[i] = wind[wind.length - 1]; wind.pop(); continue; }
          c.moveTo(p.x, p.y);
          c.lineTo(p.x - p.vx * 0.035, p.y - p.vy * 0.035);
        }
        c.stroke();
      });

      // sparkles
      for (let i = sparks.length - 1; i >= 0; i--) {
        const p = sparks[i];
        p.age += dt;
        if (p.age >= p.life) { sparks[i] = sparks[sparks.length - 1]; sparks.pop(); continue; }
        p.x += p.vx * dt;
        p.y += p.vy * dt;
        p.vx *= 0.97; p.vy *= 0.97;
        c.globalAlpha = clamp01((1 - p.age / p.life) * (0.65 + 0.35 * Math.sin(p.age * 30 + p.ph)));
        c.fillStyle = p.col;
        star(p.x, p.y, p.s);
      }
      c.globalAlpha = 1;

      raf = requestAnimationFrame(frame);
    };
    raf = requestAnimationFrame(frame);

    const tDone = window.setTimeout(finish, TOTAL_MS);

    return () => {
      cancelAnimationFrame(raf);
      window.clearTimeout(tDone);
      window.removeEventListener('resize', resize);
      stopSound();
    };
  }, []);

  const fills = ['#cf9a86', '#dca67c', '#e8bc86', '#f2cf98'];

  return (
    <div
      aria-hidden="true"
      data-gift-overlay="1"
      ref={wrapRef}
      style={{ position: 'fixed', inset: 0, zIndex: 9400, pointerEvents: 'none', overflow: 'hidden', opacity: 0 }}
    >
      <svg ref={svgRef} width="100%" height="100%" preserveAspectRatio="none" style={{ position: 'absolute', inset: 0, display: 'block' }}>
        <defs>
          <linearGradient id="hg-sky" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0" stopColor="#4f78b5" />
            <stop offset="0.45" stopColor="#e9a37b" />
            <stop offset="0.7" stopColor="#fbdca6" />
            <stop offset="1" stopColor="#f6d9a8" />
          </linearGradient>
          <radialGradient id="hg-glow">
            <stop offset="0" stopColor="rgba(255,238,190,0.9)" />
            <stop offset="1" stopColor="rgba(255,238,190,0)" />
          </radialGradient>
        </defs>
        <rect width="100%" height="100%" fill="url(#hg-sky)" />
        <circle ref={glowRef} fill="url(#hg-glow)" />
        <circle ref={sunRef} fill="#fff4cf" />
        {fills.map((f, i) => (
          <g key={i} ref={el => { layerRefs.current[i] = el; }}>
            <path ref={el => { pathRefs.current[i] = el; }} fill={f} />
          </g>
        ))}
        <g ref={camRef}>
          <ellipse ref={shadowRef} fill="rgba(90,50,25,0.3)" />
          <g ref={horseRef}><HorseParts /></g>
        </g>
      </svg>

      {/* warm sandy haze that thickens with the wind */}
      <div ref={hazeRef} style={{ position: 'absolute', inset: 0, background: 'rgba(240,200,140,1)', opacity: 0 }} />
      {/* flying dust and sparkles */}
      <canvas ref={cvRef} style={{ position: 'absolute', left: 0, top: 0, display: 'block' }} />
    </div>
  );
}

export const HorseGift: GiftDefinition = {
  id: 'horse',
  name: 'Horse',
  price: PRICE,
  durationMs: TOTAL_MS,
  Preview: HorsePreview,
  Animation: HorseAnimation,
};

export default HorseGift;
