/**
 * Storm gift (عاصفة) - 1,500 Coins
 *
 * - Preview  : a small black cloud that fills the gift square, drifting, with lightning flashes and light rain (before tapping).
 * - Animation (15 seconds):
 *      0 - 2.4s   a heavy black cloud slides down and covers the live room from the top
 *      2.7s ...   real-looking lightning bolts tear across the screen, with thunder
 *      5.4s ...   the sky opens: rain starts light and becomes heavy
 *      rain drops fall on the screen, and splash / run down on the icons and buttons of the live room
 *      ~13.4s     the rain calms, the cloud fades and the live room comes back
 *
 * Lift mode (NEW) - when the host gives this gift to a USER (not to himself):
 *      3.0 - 4.4s   the user's picture rises from his place to the middle of the live (his original picture is hidden)
 *      5.3s         a huge lightning bolt hits the picture's FRAME  (the frame flashes)
 *      6.5s         a second lightning bolt hits the frame again
 *      7.0 - 7.5s   the picture vanishes with the last flash and goes back to its place
 *   It uses the same data as the Volcano gift: window.__stooornaGiftLift (set by LiveCoinsDock) + [data-gift-user].
 *   If the gift is not for a user, the animation is exactly the same as before.
 *
 * Standalone file: put it in src/components/gifts/ next to HeartGift.tsx and WitchGift.tsx.
 * The sounds are generated by src/lib/stormSounds.ts (no audio files needed).
 * To use real recordings, put them in the PUBLIC folder and set the two URLs below:
 *     public/sounds/storm-thunder.mp3
 *     public/sounds/storm-rain.mp3
 * If a file is missing or cannot be decoded, the generated sound is played instead.
 */
import React, { useEffect, useRef } from 'react';
import type { GiftDefinition } from '../../lib/types';
import { playStormSound } from '../../lib/stormSounds';

// ── Gift settings ────────────────────────────────────────────────────────
const PRICE = 1500;
const TOTAL_MS = 15000;          // the whole gift lasts 15 seconds
const TOTAL_S = TOTAL_MS / 1000;
const FADE_IN_S = 0.7;           // overlay fades in
const FADE_OUT_S = 1.4;          // overlay fades out at the end
const CLOUD_DROP_S = 2.4;        // time the cloud takes to come down
const CLOUD_COVER = 0.6;         // how much of the screen height the cloud covers (0..1)
const RAIN_FROM = 5.4;           // rain starts (seconds)
const RAIN_FULL = 7.4;           // rain reaches full strength
const RAIN_FADE_S = 1.8;         // rain calms down during the last seconds
const RAIN_DENSITY = 1.7;        // more = heavier rain
const RAIN_ON_UI = 0.45;         // share of the drops that land on icons / buttons (0..1)
const THUNDER_URL: string | undefined = undefined; // e.g. '/sounds/storm-thunder.mp3'
const RAIN_URL: string | undefined = undefined;    // e.g. '/sounds/storm-rain.mp3'

const VIOLET = '#8b9cff';

// Lift mode timeline (seconds)
const AV_UP_AT = 3.0;            // the user's picture starts to rise
const AV_UP_S = 1.4;             // rising duration
const AV_HIT1 = 5.3;             // first lightning bolt on the frame
const AV_HIT2 = 6.5;             // second lightning bolt on the frame
const AV_FADE_AT = 7.0;          // the picture vanishes
const AV_FADE_S = 0.5;

// Lightning timeline. t = seconds from start, x = horizontal position (0..1),
// big = a huge bolt that splits the whole screen, lag = delay before the thunder reaches us.
interface Strike { t: number; x: number; big: boolean; lag: number; power: number; tx?: number; ty?: number }
const STRIKES: Strike[] = [
  { t: 2.7, x: 0.3, big: false, lag: 0.45, power: 0.6 },
  { t: 4.6, x: 0.68, big: true, lag: 0.07, power: 1 },
  { t: 7.5, x: 0.42, big: true, lag: 0.1, power: 0.95 },
  { t: 10.2, x: 0.17, big: false, lag: 0.4, power: 0.65 },
  { t: 11.9, x: 0.8, big: true, lag: 0.08, power: 1 },
];

// ── Small helpers ────────────────────────────────────────────────────────
const clamp01 = (x: number) => Math.min(1, Math.max(0, x));
const smooth = (x: number) => { const u = clamp01(x); return u * u * (3 - 2 * u); };
const easeOut = (x: number) => 1 - Math.pow(1 - clamp01(x), 3);
const lerp = (a: number, b: number, u: number) => a + (b - a) * u;

// ── Styles (cloud blobs, preview animation) ─────────────────────────────────
const CSS = `
@keyframes sg-drift { from { transform: translate3d(calc(var(--dx) * -1),0,0); } to { transform: translate3d(var(--dx),0,0); } }
@keyframes sg-pv-flash { 0%,38%,52%,100% { opacity:0; } 40% { opacity:.95; } 43% { opacity:.15; } 46% { opacity:.8; } 50% { opacity:0; } }
@keyframes sg-pv-rain { from { background-position: 0 0, 0 0; } to { background-position: -14px 44px, -9px 66px; } }
@keyframes sg-pv-pulse { 0%,100% { opacity:.55; } 50% { opacity:.9; } }
@media (prefers-reduced-motion: reduce) { .sg-blob, .sg-pv-rain, .sg-pv-flash { animation: none !important; } }
`;

// deterministic pseudo random so the cloud looks the same every time
const rnd = (i: number, n: number) => { const x = Math.sin(i * 127.1 + n * 311.7) * 43758.5453; return x - Math.floor(x); };

const BLOBS = Array.from({ length: 18 }, (_, i) => ({
  left: -18 + (i % 9) * 13 + rnd(i, 1) * 8,
  top: 34 + Math.floor(i / 9) * 22 + rnd(i, 2) * 20,
  w: 40 + rnd(i, 3) * 34,
  dur: 6 + rnd(i, 4) * 6,
  dx: (rnd(i, 5) > 0.5 ? 1 : -1) * (2 + rnd(i, 7) * 3),
  delay: -rnd(i, 6) * 8,
  a: 0.86 + rnd(i, 8) * 0.12,
}));

const PV_BLOBS = [
  { l: -20, t: -18, w: 70, dur: 7, dx: 6, d: 0 },
  { l: 20, t: -22, w: 80, dur: 9, dx: -6, d: -2 },
  { l: 50, t: -16, w: 70, dur: 8, dx: 5, d: -4 },
  { l: -10, t: 8, w: 60, dur: 6, dx: -5, d: -1 },
  { l: 35, t: 6, w: 70, dur: 7.5, dx: 5, d: -3 },
  { l: 62, t: 10, w: 50, dur: 6.5, dx: -4, d: -5 },
];

// ── Preview inside the gift square: black cloud + flashes + light rain ──────
function StormPreview({ size = 72 }: { size?: number }) {
  const s = Math.round(size * 1.2);
  return (
    <div
      aria-hidden="true"
      style={{
        position: 'relative', width: s, height: s, borderRadius: 16, overflow: 'hidden',
        boxShadow: `0 0 0 1.5px ${VIOLET}, 0 0 12px rgba(139,156,255,0.5)`,
        background: 'linear-gradient(180deg,#04060b 0%,#0c1222 100%)',
      }}
    >
      <style>{CSS}</style>

      {/* light rain under the cloud */}
      <div
        className="sg-pv-rain"
        style={{
          position: 'absolute', inset: 0,
          backgroundImage:
            'repeating-linear-gradient(104deg, rgba(180,205,255,0.55) 0 1px, transparent 1px 9px), repeating-linear-gradient(104deg, rgba(150,180,255,0.35) 0 1px, transparent 1px 13px)',
          backgroundSize: '14px 44px, 9px 66px',
          WebkitMaskImage: 'linear-gradient(to bottom, transparent 30%, #000 60%, #000 100%)',
          maskImage: 'linear-gradient(to bottom, transparent 30%, #000 60%, #000 100%)',
          animation: 'sg-pv-rain 0.55s linear infinite',
          opacity: 0.8,
        }}
      />

      {/* black cloud covering the square */}
      <div style={{ position: 'absolute', inset: 0 }}>
        <div
          style={{
            position: 'absolute', left: 0, right: 0, top: 0, height: '62%',
            background: 'linear-gradient(to bottom, rgba(3,4,8,1) 0%, rgba(6,8,13,0.96) 60%, rgba(6,8,13,0) 100%)',
          }}
        />
        {PV_BLOBS.map((b, i) => (
          <div
            key={i}
            className="sg-blob"
            style={{
              position: 'absolute', left: `${b.l}%`, top: `${b.t}%`,
              width: `${b.w}%`, height: `${b.w * 0.75}%`,
              background: 'radial-gradient(ellipse at 50% 50%, rgba(12,15,24,0.98) 0%, rgba(8,10,17,0.85) 45%, rgba(8,10,17,0) 72%)',
              ['--dx' as string]: `${b.dx}%`,
              animation: `sg-drift ${b.dur}s ease-in-out ${b.d}s infinite alternate`,
            } as React.CSSProperties}
          />
        ))}
      </div>

      {/* lightning flash + bolt */}
      <div
        className="sg-pv-flash"
        style={{
          position: 'absolute', inset: 0, opacity: 0,
          background: 'radial-gradient(circle at 62% 8%, rgba(210,225,255,0.85), rgba(120,140,255,0.15) 55%, transparent 80%)',
          animation: 'sg-pv-flash 2.6s linear infinite',
        }}
      />
      <svg
        className="sg-pv-flash"
        viewBox="0 0 100 100"
        style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', opacity: 0, animation: 'sg-pv-flash 2.6s linear infinite' }}
      >
        <polyline points="62,18 55,36 63,40 52,62 58,66 47,90" fill="none" stroke="rgba(150,175,255,0.8)" strokeWidth="5" strokeLinejoin="round" strokeLinecap="round" />
        <polyline points="62,18 55,36 63,40 52,62 58,66 47,90" fill="none" stroke="#fff" strokeWidth="1.8" strokeLinejoin="round" strokeLinecap="round" />
      </svg>
    </div>
  );
}

// ── Lightning geometry ──────────────────────────────────────────────────────
type Pt = { x: number; y: number };
interface Bolt { main: Pt[]; branches: Pt[][] }

function jag(x0: number, y0: number, x1: number, y1: number, rough: number, depth: number): Pt[] {
  let pts: Pt[] = [{ x: x0, y: y0 }, { x: x1, y: y1 }];
  let d = rough;
  for (let i = 0; i < depth; i++) {
    const next: Pt[] = [pts[0]];
    for (let j = 0; j < pts.length - 1; j++) {
      const a = pts[j], b = pts[j + 1];
      next.push({ x: (a.x + b.x) / 2 + (Math.random() - 0.5) * d, y: (a.y + b.y) / 2 + (Math.random() - 0.5) * d * 0.35 });
      next.push(b);
    }
    pts = next;
    d *= 0.55;
  }
  return pts;
}

function makeBolt(st: Strike, W: number, H: number): Bolt {
  const x0 = st.x * W;
  const y0 = st.big ? 0 : H * CLOUD_COVER * 0.45;
  const x1 = st.tx !== undefined ? st.tx : x0 + (Math.random() - 0.5) * W * 0.35;
  const y1 = st.ty !== undefined ? st.ty : (st.big ? H * (0.8 + Math.random() * 0.15) : H * (0.42 + Math.random() * 0.15));
  const main = jag(x0, y0, x1, y1, W * 0.28, 6);
  const branches: Pt[][] = [];
  const nb = st.big ? 5 : 3;
  for (let b = 0; b < nb; b++) {
    const k = Math.floor(main.length * (0.2 + Math.random() * 0.6));
    const p = main[k];
    const dir = Math.random() < 0.5 ? -1 : 1;
    const bx = p.x + dir * (W * (0.1 + Math.random() * 0.25));
    const by = p.y + H * (0.08 + Math.random() * 0.2);
    branches.push(jag(p.x, p.y, bx, by, W * 0.14, 4));
  }
  return { main, branches };
}

// brightness of a strike over time: quick double / triple flicker, then fade
function flick(e: number, big: boolean): number {
  if (e < 0) return 0;
  if (e < 0.07) return 1;
  if (e < 0.12) return 0.2;
  if (e < 0.22) return 0.95;
  if (e < 0.27) return 0.3;
  if (!big) return Math.max(0, 0.45 * (1 - (e - 0.27) / 0.3));
  if (e < 0.38) return 0.9;
  return Math.max(0, 0.6 * (1 - (e - 0.38) / 0.7));
}

// ── Lift mode helpers (the gift is for a user: his picture rises and the lightning hits its frame) ──
interface LiftInfo { userId: string; name?: string; avatarUrl?: string | null }
interface LiftAv {
  sx: number; sy: number; sr: number;
  img: HTMLImageElement | null; letter: string; name: string;
  restore: () => void; done?: boolean;
}

// LiveCoinsDock puts the receiver in window.__stooornaGiftLift (only when the gift is for a user, not for the host)
function getLiftInfo(): LiftInfo | null {
  try {
    const d = (window as unknown as { __stooornaGiftLift?: LiftInfo }).__stooornaGiftLift;
    return d && d.userId ? d : null;
  } catch { return null; }
}

function findLiftAv(W: number, H: number, pre: HTMLImageElement | null): LiftAv | null {
  try {
    const info = getLiftInfo();
    if (!info) return null;
    let el: HTMLElement | null = null;
    try { el = document.querySelector<HTMLElement>(`[data-gift-user="${String(info.userId).replace(/["\\]/g, '')}"]`); } catch { /* ignore */ }
    const r = el ? el.getBoundingClientRect() : null;
    const hasEl = !!(el && r && r.width > 0 && r.height > 0);
    const elImg = el ? el.querySelector('img') : null;
    const useImg = pre && pre.complete && pre.naturalWidth > 0 ? pre : (elImg && elImg.complete && elImg.naturalWidth > 0 ? elImg : pre);
    const nm = String(info.name || (el?.textContent || '') || '?').trim();
    const prevOp = hasEl ? el!.style.opacity : '';
    if (hasEl) el!.style.opacity = '0.12';
    return {
      sx: hasEl ? r!.left + r!.width / 2 : W - 52,
      sy: hasEl ? r!.top + r!.height / 2 : H * 0.55,
      sr: hasEl ? r!.width / 2 : 20,
      img: useImg || null,
      letter: (nm.charAt(0) || '?').toUpperCase(),
      name: nm,
      restore: () => { try { if (hasEl) el!.style.opacity = prevOp; } catch { /* ignore */ } },
    };
  } catch { return null; }
}

// ── Full-screen animation: cloud, lightning, thunder, rain on the live room ──
interface Drop { x: number; y: number; vy: number; len: number; landY: number; hit: boolean }
interface Splash { x: number; y: number; vx: number; vy: number; age: number; life: number }
interface Bead { x: number; y: number; vy: number; age: number; life: number; r: number }
interface UiRect { left: number; top: number; width: number; height: number }

function StormAnimation({ onDone }: { onDone: () => void }) {
  const doneRef = useRef(onDone);
  doneRef.current = onDone;
  const wrapRef = useRef<HTMLDivElement>(null);
  const cloudRef = useRef<HTMLDivElement>(null);
  const dimRef = useRef<HTMLDivElement>(null);
  const cvRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const wrap = wrapRef.current;
    const cloud = cloudRef.current;
    const dim = dimRef.current;
    const cv = cvRef.current;
    if (!wrap || !cloud || !dim || !cv) return;
    const c = cv.getContext('2d');
    if (!c) return;

    let finished = false;
    const finish = () => {
      if (finished) return;
      finished = true;
      doneRef.current();
    };

    // size / canvas
    let W = window.innerWidth;
    let H = window.innerHeight;
    const resize = () => {
      W = window.innerWidth;
      H = window.innerHeight;
      const dpr = Math.min(2, window.devicePixelRatio || 1);
      cv.width = Math.round(W * dpr);
      cv.height = Math.round(H * dpr);
      cv.style.width = W + 'px';
      cv.style.height = H + 'px';
      c.setTransform(dpr, 0, 0, dpr, 0, 0);
    };
    resize();
    window.addEventListener('resize', resize);

    // lift mode: the picture of the receiver rises to the middle, the lightning hits its frame twice
    const liftInfo0 = getLiftInfo();
    let liftPre: HTMLImageElement | null = null;
    if (liftInfo0 && liftInfo0.avatarUrl) {
      try { liftPre = new Image(); liftPre.src = String(liftInfo0.avatarUrl); } catch { liftPre = null; }
    }
    let lift: LiftAv | null = null;
    const AVR = Math.max(40, Math.min(64, W * 0.16));
    const AVX = W * 0.5;
    const AVY = H * 0.4;
    const strikes: Strike[] = STRIKES.slice();
    if (liftInfo0) {
      strikes.push({ t: AV_HIT1, x: 0.5, big: true, lag: 0.05, power: 1, tx: AVX - AVR * 0.25, ty: AVY - AVR * 0.95 });
      strikes.push({ t: AV_HIT2, x: 0.58, big: true, lag: 0.05, power: 1, tx: AVX + AVR * 0.7, ty: AVY - AVR * 0.7 });
      strikes.sort((a, b) => a.t - b.t);
    }

    // sound
    const stopSound = playStormSound({
      thunders: strikes.map(s => ({ t: s.t + s.lag, power: s.power })),
      rainFrom: RAIN_FROM,
      rainTo: TOTAL_S - 0.4,
      totalS: TOTAL_S,
      thunderUrl: THUNDER_URL,
      rainUrl: RAIN_URL,
    });

    // lightning bolts (geometry made once per strike, when it first shows)
    const bolts: (Bolt | null)[] = strikes.map(() => null);

    // icons and buttons of the live room: the rain lands and splashes on them
    let rects: UiRect[] = [];
    const collectRects = () => {
      const out: UiRect[] = [];
      const nodes = document.querySelectorAll('button, [role="button"], a, img, svg, input, textarea');
      nodes.forEach(el => {
        if (out.length >= 140) return;
        if ((el as Element).closest('[data-gift-overlay]')) return;
        const r = el.getBoundingClientRect();
        if (r.width < 14 || r.height < 14) return;
        if (r.width > W * 0.92 || r.height > H * 0.5) return;
        if (r.bottom <= 0 || r.top >= H || r.right <= 0 || r.left >= W) return;
        out.push({ left: r.left, top: r.top, width: r.width, height: r.height });
      });
      rects = out;
    };
    collectRects();
    const rectTimer = window.setInterval(collectRects, 450);

    // rain state
    const drops: Drop[] = [];
    const splashes: Splash[] = [];
    const beads: Bead[] = [];
    const WIND = 110;
    let spawnAcc = 0;

    const spawnDrop = () => {
      const vy = 950 + Math.random() * 500;
      const len = 14 + Math.random() * 16;
      if (rects.length && Math.random() < RAIN_ON_UI) {
        const r = rects[(Math.random() * rects.length) | 0];
        const lx = r.left + Math.random() * r.width;
        const ly = r.top + Math.random() * Math.min(r.height * 0.35, 14);
        const T = (ly + len) / vy;
        drops.push({ x: lx - WIND * T, y: -len, vy, len, landY: ly, hit: true });
      } else {
        drops.push({ x: Math.random() * (W + WIND * 1.4) - WIND * 1.4, y: -len, vy, len, landY: H + len, hit: false });
      }
    };

    const addSplash = (x: number, y: number) => {
      const n = 4 + ((Math.random() * 3) | 0);
      for (let i = 0; i < n && splashes.length < 700; i++) {
        splashes.push({ x, y, vx: (Math.random() - 0.5) * 120, vy: -(70 + Math.random() * 110), age: 0, life: 0.26 + Math.random() * 0.14 });
      }
      if (Math.random() < 0.5 && beads.length < 180) {
        beads.push({ x, y: y + 2, vy: 18 + Math.random() * 34, age: 0, life: 0.8 + Math.random() * 0.5, r: 1.6 + Math.random() * 1.6 });
      }
    };

    const drawPath = (pts: Pt[]) => {
      c.beginPath();
      c.moveTo(pts[0].x, pts[0].y);
      for (let i = 1; i < pts.length; i++) c.lineTo(pts[i].x, pts[i].y);
      c.stroke();
    };

    const drawBolt = (b: Bolt, a: number, big: boolean) => {
      c.lineJoin = 'round';
      c.lineCap = 'round';
      const layers: [string, number][] = [
        [`rgba(110,130,255,${0.22 * a})`, big ? 16 : 10],
        [`rgba(160,185,255,${0.5 * a})`, big ? 7 : 4.5],
        [`rgba(255,255,255,${Math.min(1, a * 1.1)})`, big ? 2.4 : 1.6],
      ];
      layers.forEach(([col, w]) => {
        c.strokeStyle = col;
        c.lineWidth = w;
        drawPath(b.main);
        c.lineWidth = Math.max(1, w * 0.55);
        b.branches.forEach(drawPath);
      });
    };

    let raf = 0;
    const t0 = performance.now();
    let last = t0;

    const frame = (now: number) => {
      const t = (now - t0) / 1000;
      const dt = Math.min(0.05, (now - last) / 1000);
      last = now;

      // overlay fade + cloud coming down
      wrap.style.opacity = String(clamp01(t / FADE_IN_S) * clamp01((TOTAL_S - t) / FADE_OUT_S));
      const e = easeOut(t / CLOUD_DROP_S);
      cloud.style.transform = `translate3d(0, ${(-(1 - e) * 100).toFixed(2)}%, 0)`;
      dim.style.opacity = String(0.15 + 0.85 * e);

      c.clearRect(0, 0, W, H);

      // the user's picture (lift mode): rises to the middle, then the lightning hits its frame
      let avE = 0, avX = 0, avY = 0, avR = 0, hitF = 0;
      if (liftInfo0) {
        if (!lift && t >= AV_UP_AT - 0.4) lift = findLiftAv(W, H, liftPre);
        if (lift) {
          const up = easeOut((t - AV_UP_AT) / AV_UP_S);
          const out = smooth((t - AV_FADE_AT) / AV_FADE_S);
          avE = up * (1 - out);
          if (out >= 1 && !lift.done) { lift.done = true; lift.restore(); }
          if (avE > 0.004) {
            avX = lerp(lift.sx, AVX, up);
            avY = lerp(lift.sy, AVY, up) + Math.sin(t * 2.6) * 3 * avE;
            avR = lerp(lift.sr, AVR, up) * (1 + 0.12 * out);
            hitF = Math.max(flick(t - AV_HIT1, true), flick(t - AV_HIT2, true));

            const ag = c.createRadialGradient(avX, avY, avR * 0.6, avX, avY, avR * 2.6);
            ag.addColorStop(0, `rgba(120,140,255,${0.34 * avE})`);
            ag.addColorStop(1, 'rgba(120,140,255,0)');
            c.fillStyle = ag;
            c.beginPath(); c.arc(avX, avY, avR * 2.6, 0, Math.PI * 2); c.fill();

            c.save();
            c.globalAlpha = clamp01(avE * 3);
            c.beginPath(); c.arc(avX, avY, avR, 0, Math.PI * 2); c.closePath();
            c.save();
            c.clip();
            let drawn = false;
            if (!lift.img && liftPre && liftPre.complete && liftPre.naturalWidth > 0) lift.img = liftPre;
            if (lift.img && lift.img.complete && lift.img.naturalWidth > 0) {
              try {
                const sw = lift.img.naturalWidth, sh = lift.img.naturalHeight, ss = Math.min(sw, sh);
                c.drawImage(lift.img, (sw - ss) / 2, (sh - ss) / 2, ss, ss, avX - avR, avY - avR, avR * 2, avR * 2);
                drawn = true;
              } catch { /* ignore */ }
            }
            if (!drawn) {
              c.fillStyle = '#101530';
              c.fillRect(avX - avR, avY - avR, avR * 2, avR * 2);
              c.fillStyle = VIOLET;
              c.font = `800 ${Math.round(avR * 1.0)}px sans-serif`;
              c.textAlign = 'center';
              c.textBaseline = 'middle';
              c.fillText(lift.letter, avX, avY + avR * 0.04);
            }
            if (hitF > 0.02) {
              c.fillStyle = `rgba(210,225,255,${0.55 * hitF})`;
              c.fillRect(avX - avR, avY - avR, avR * 2, avR * 2);
            }
            c.restore();
            c.beginPath(); c.arc(avX, avY, avR, 0, Math.PI * 2);
            c.lineWidth = Math.max(2.4, avR * 0.08);
            c.strokeStyle = VIOLET;
            c.shadowColor = 'rgba(139,156,255,0.9)';
            c.shadowBlur = 12;
            c.stroke();
            c.restore();

            if (avE > 0.5) {
              c.save();
              c.globalAlpha = clamp01((avE - 0.5) * 2);
              c.font = `800 ${Math.round(Math.max(12, avR * 0.3))}px sans-serif`;
              c.textAlign = 'center';
              c.textBaseline = 'top';
              c.shadowColor = 'rgba(0,0,0,0.9)';
              c.shadowBlur = 6;
              c.fillStyle = '#e6ebff';
              c.fillText(lift.name.length > 18 ? lift.name.slice(0, 17) + '…' : lift.name, avX, avY + avR + 8);
              c.restore();
            }
          }
        }
      }

      // lightning
      for (let i = 0; i < strikes.length; i++) {
        const st = strikes[i];
        const f = flick(t - st.t, st.big);
        if (f <= 0.01) continue;
        if (!bolts[i]) bolts[i] = makeBolt(st, W, H);

        // light that fills the sky around the bolt
        const gx = st.x * W;
        const g = c.createRadialGradient(gx, 0, 0, gx, 0, H * 0.95);
        g.addColorStop(0, `rgba(215,228,255,${(st.big ? 0.75 : 0.42) * f})`);
        g.addColorStop(0.5, `rgba(120,140,255,${(st.big ? 0.28 : 0.14) * f})`);
        g.addColorStop(1, 'rgba(90,110,255,0)');
        c.fillStyle = g;
        c.fillRect(0, 0, W, H);
        if (st.big) {
          c.fillStyle = `rgba(205,220,255,${0.3 * f})`;
          c.fillRect(0, 0, W, H);
        }
        if (f > 0.15) drawBolt(bolts[i] as Bolt, Math.min(1, f * 1.15), st.big);
      }

      // lightning flash ON the frame of the lifted picture (twice) + electric arcs running around it
      if (avE > 0.004 && hitF > 0.05) {
        c.save();
        c.globalAlpha = clamp01(avE * 3);
        c.beginPath(); c.arc(avX, avY, avR, 0, Math.PI * 2);
        c.strokeStyle = `rgba(255,255,255,${Math.min(1, hitF * 1.1)})`;
        c.lineWidth = Math.max(3, avR * 0.12);
        c.shadowColor = 'rgba(150,175,255,1)';
        c.shadowBlur = 30 * hitF;
        c.stroke();
        c.shadowBlur = 0;
        c.lineJoin = 'round';
        c.lineCap = 'round';
        for (let k = 0; k < 8; k++) {
          const ang = (k / 8) * Math.PI * 2 + t * 3 + Math.random() * 0.4;
          const ca = Math.cos(ang), sa = Math.sin(ang);
          const arc = jag(avX + ca * avR, avY + sa * avR, avX + ca * avR * (1.35 + Math.random() * 0.4), avY + sa * avR * (1.35 + Math.random() * 0.4), avR * 0.3, 3);
          c.strokeStyle = `rgba(150,175,255,${0.55 * hitF})`;
          c.lineWidth = 4;
          drawPath(arc);
          c.strokeStyle = `rgba(255,255,255,${Math.min(1, hitF)})`;
          c.lineWidth = 1.4;
          drawPath(arc);
        }
        c.restore();
      }

      // rain
      const rainI = smooth((t - RAIN_FROM) / (RAIN_FULL - RAIN_FROM)) * clamp01((TOTAL_S - 0.4 - t) / RAIN_FADE_S);
      spawnAcc += rainI * W * RAIN_DENSITY * dt;
      while (spawnAcc >= 1 && drops.length < 950) { spawnAcc -= 1; spawnDrop(); }

      c.strokeStyle = 'rgba(190,212,255,0.5)';
      c.lineWidth = 1.2;
      c.lineCap = 'round';
      c.beginPath();
      for (let i = drops.length - 1; i >= 0; i--) {
        const d = drops[i];
        d.y += d.vy * dt;
        d.x += WIND * dt;
        if (d.y >= d.landY) {
          if (d.hit) addSplash(d.x, d.landY);
          drops[i] = drops[drops.length - 1];
          drops.pop();
          continue;
        }
        const k = d.len / Math.hypot(WIND, d.vy);
        c.moveTo(d.x, d.y);
        c.lineTo(d.x - WIND * k, d.y - d.vy * k);
      }
      c.stroke();

      // splashes
      c.fillStyle = 'rgba(215,230,255,0.85)';
      for (let i = splashes.length - 1; i >= 0; i--) {
        const s = splashes[i];
        s.age += dt;
        if (s.age >= s.life) { splashes[i] = splashes[splashes.length - 1]; splashes.pop(); continue; }
        s.vy += 700 * dt;
        s.x += s.vx * dt;
        s.y += s.vy * dt;
        c.globalAlpha = 1 - s.age / s.life;
        c.beginPath();
        c.arc(s.x, s.y, 1.3, 0, Math.PI * 2);
        c.fill();
      }
      c.globalAlpha = 1;

      // water beads that slide down the icons and buttons
      for (let i = beads.length - 1; i >= 0; i--) {
        const b = beads[i];
        b.age += dt;
        if (b.age >= b.life) { beads[i] = beads[beads.length - 1]; beads.pop(); continue; }
        b.y += b.vy * dt;
        const a = 1 - b.age / b.life;
        c.fillStyle = `rgba(200,220,255,${0.5 * a})`;
        c.beginPath();
        c.ellipse(b.x, b.y, b.r * 0.8, b.r * 1.25, 0, 0, Math.PI * 2);
        c.fill();
        c.fillStyle = `rgba(255,255,255,${0.7 * a})`;
        c.beginPath();
        c.arc(b.x - b.r * 0.25, b.y - b.r * 0.35, b.r * 0.3, 0, Math.PI * 2);
        c.fill();
      }

      raf = requestAnimationFrame(frame);
    };
    raf = requestAnimationFrame(frame);

    const tDone = window.setTimeout(finish, TOTAL_MS);

    return () => {
      cancelAnimationFrame(raf);
      window.clearTimeout(tDone);
      window.clearInterval(rectTimer);
      window.removeEventListener('resize', resize);
      stopSound();
      if (lift && !lift.done) { lift.done = true; lift.restore(); }
    };
  }, []);

  return (
    <div
      aria-hidden="true"
      data-gift-overlay="1"
      ref={wrapRef}
      style={{ position: 'fixed', inset: 0, zIndex: 9400, pointerEvents: 'none', overflow: 'hidden', opacity: 0 }}
    >
      <style>{CSS}</style>

      {/* the whole sky gets darker */}
      <div ref={dimRef} style={{ position: 'absolute', inset: 0, background: 'rgba(2,4,9,0.42)', opacity: 0 }} />

      {/* black cloud sliding down from the top */}
      <div
        ref={cloudRef}
        style={{
          position: 'absolute', left: 0, right: 0, top: 0, height: `${CLOUD_COVER * 100}%`,
          transform: 'translate3d(0,-100%,0)', willChange: 'transform',
          background: 'linear-gradient(to bottom, rgba(2,3,6,1) 0%, rgba(5,7,12,0.97) 55%, rgba(5,7,12,0) 100%)',
        }}
      >
        {BLOBS.map((b, i) => (
          <div
            key={i}
            className="sg-blob"
            style={{
              position: 'absolute', left: `${b.left}%`, top: `${b.top}%`,
              width: `${b.w}vw`, height: `${b.w * 0.72}vw`,
              background: `radial-gradient(ellipse at 50% 50%, rgba(11,14,22,${b.a}) 0%, rgba(8,10,17,${b.a * 0.82}) 45%, rgba(8,10,17,0) 72%)`,
              ['--dx' as string]: `${b.dx}vw`,
              animation: `sg-drift ${b.dur}s ease-in-out ${b.delay}s infinite alternate`,
            } as React.CSSProperties}
          />
        ))}
      </div>

      {/* lightning + rain */}
      <canvas ref={cvRef} style={{ position: 'absolute', left: 0, top: 0, display: 'block' }} />
    </div>
  );
}

export const StormGift: GiftDefinition = {
  id: 'storm',
  name: 'Storm',
  price: PRICE,
  durationMs: TOTAL_MS,
  Preview: StormPreview,
  Animation: StormAnimation,
};

export default StormGift;
