[build]
  command = "npm install && npm run build"
  publish = "dist/client"

[[redirects]]
  from = "/api/*"
  to = "https://stoooorna.onrender.com/api/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200