// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const pages: { "add_friend": { "QUICK_EMOJIS": Array<string> }; "home": { "appName": string; "channelSearch": string; "whisperLabel": string }; "live": { "seo": { "title": string; "description": string; "heading": string } }; "privacy": { "VISIBILITY_OPTIONS": Array<{ "value": string; "label": string; "id": string }> }; "share": { "bars": Array<number> } };
  export const add_friend: { "QUICK_EMOJIS": Array<string> };
  export const home: { "appName": string; "channelSearch": string; "whisperLabel": string };
  export const live: { "seo": { "title": string; "description": string; "heading": string } };
  export const privacy: { "VISIBILITY_OPTIONS": Array<{ "value": string; "label": string; "id": string }> };
  export const share: { "bars": Array<number> };
}
